# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - android
      - linux
      - windows
      - darwin
    #      - freebsd
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - '5'
      - '6'
      - '7'
    gomips:
      - hardfloat
      - softfloat
    ignore:
      # we only need the arm64 build on android
      - goos: android
        goarch: arm
      - goos: android
        goarch: '386'
      - goos: android
        goarch: amd64
    ldflags:
      - -s -w -X github.com/mDNSService/onvif-viewer/info.Version={{.Version}} -X github.com/mDNSService/onvif-viewer/info.Commit={{.Commit}} -X github.com/mDNSService/onvif-viewer/info.Date={{ .CommitDate }} -X github.com/mDNSService/onvif-viewer/info.BuiltBy=goreleaser

archives:
  # use zip for windows archives
  - format_overrides:
      - goos: windows
        format: zip
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-devel"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage:  http://github.com/mDNSService
    description: mDNSService GateWay
    maintainer: mDNSService <newfarry@126.com>
    license: MIT
    vendor: onvif-viewer
    formats:
      - deb
      - rpm
    scripts:
      preinstall: "scripts/install_remove/preinstall.sh"
      postinstall: "scripts/install_remove/postinstall.sh"
      preremove: "scripts/install_remove/preremove.sh"
      postremove: "scripts/install_remove/postremove.sh"
    contents:
      - src: systemd/**
        dst: /etc/systemd/system
      - src: onvif-viewer.yaml
        dst: /etc/onvif-viewer/onvif-viewer.yaml
        type: config
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    summary: mDNSService GateWay.
    description: |
      mDNSService GateWay
    grade: stable
    confinement: strict
    #    confinement: classic
    publish: true
    apps:
      onvif-viewer:
        plugs: ["network", "network-bind"]
        daemon: simple
        command: onvif-viewer
dockers:
  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64

  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-armv7"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm
    goarm: 7

docker_manifests:
  - name_template: "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-arm64"
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-armv7"

  - name_template: "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:latest"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-arm64"
      - "{{ .Env.DOCKER_USERNAME }}/onvif-viewer:{{ .Tag }}-armv7"

  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"

  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"